# GitHub Linguist Override Configuration
# This provides additional language detection hints

# Override for specific paths
scripts/groovy:
  - "*.groovy"

utils:
  - "*.py"
  - "*.sh"

# Language order preference (most important first)
languages:
  - Groovy
  - Python
  - Shell
  - YAML

